"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { formatDistanceToNow } from "date-fns";
import { FileEdit, Check, X, Sparkles } from "lucide-react";
import { draftsApi } from "@/lib/api";
import { PageHeader, EmptyState, LoadingSpinner, StatusBadge } from "@/components/dashboard";
import { Button } from "@/components/ui/button";
import { Card } from "@/components/ui/card";

export default function DraftsPage() {
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["drafts"],
    queryFn: () => draftsApi.list(),
  });

  const approveMutation = useMutation({
    mutationFn: (id: string) => draftsApi.approve(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["drafts"] }),
  });

  const rejectMutation = useMutation({
    mutationFn: (id: string) => draftsApi.reject(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["drafts"] }),
  });

  const drafts = data?.data?.drafts || [];

  return (
    <div className="max-w-4xl">
      <PageHeader
        title="Drafts"
        description="AI-generated responses waiting for your review"
      />

      {/* Content */}
      {isLoading ? (
        <LoadingSpinner className="py-16" label="Loading drafts..." />
      ) : drafts.length === 0 ? (
        <EmptyState
          icon={FileEdit}
          title="No drafts yet"
          description="AI-generated email responses will appear here for your approval"
        />
      ) : (
        <div className="space-y-3">
          {drafts.map((draft: any) => (
            <Card key={draft.id} className="p-4">
              <div className="flex items-start justify-between gap-4">
                {/* Content */}
                <div className="flex-1 min-w-0">
                  {/* Status and time */}
                  <div className="flex items-center gap-2 mb-2">
                    <StatusBadge status={draft.status} />
                    <span className="text-xs text-muted-foreground">
                      {formatDistanceToNow(new Date(draft.created_at), {
                        addSuffix: true,
                      })}
                    </span>
                  </div>

                  {/* Recipients and subject */}
                  <p className="font-medium text-sm mb-0.5">
                    To: {draft.to_emails.join(", ")}
                  </p>
                  <p className="text-sm text-muted-foreground truncate mb-2">
                    {draft.subject}
                  </p>

                  {/* Full draft body */}
                  <div className="text-sm text-muted-foreground bg-muted/50 rounded-lg p-3 whitespace-pre-wrap">
                    {draft.body_text}
                  </div>

                  {/* Model attribution */}
                  {draft.llm_model_used && (
                    <div className="flex items-center gap-1.5 mt-2 text-xs text-muted-foreground">
                      <Sparkles className="h-3 w-3" />
                      Generated by {draft.llm_model_used}
                    </div>
                  )}
                </div>

                {/* Actions */}
                {draft.status === "pending" && (
                  <div className="flex flex-col gap-2 shrink-0">
                    <Button
                      size="sm"
                      onClick={() => approveMutation.mutate(draft.id)}
                      disabled={
                        approveMutation.isPending || rejectMutation.isPending
                      }
                      className="bg-success hover:bg-success/90 text-success-foreground gap-2"
                    >
                      <Check className="h-4 w-4" />
                      Approve
                    </Button>
                    <Button
                      size="sm"
                      variant="outline"
                      onClick={() => rejectMutation.mutate(draft.id)}
                      disabled={
                        approveMutation.isPending || rejectMutation.isPending
                      }
                      className="text-destructive border-destructive/30 hover:bg-destructive/10 hover:text-destructive gap-2"
                    >
                      <X className="h-4 w-4" />
                      Reject
                    </Button>
                  </div>
                )}
              </div>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
}
