"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { formatDistanceToNow } from "date-fns";
import { FileEdit, Check, X, Sparkles, Send } from "lucide-react";
import { draftsApi } from "@/lib/api";
import { cn } from "@/lib/utils";

const statusConfig: Record<
  string,
  { label: string; className: string; icon?: typeof Check }
> = {
  pending: {
    label: "Pending Review",
    className: "badge-pending",
  },
  approved: {
    label: "Approved",
    className: "badge-approved",
  },
  sent: {
    label: "Sent",
    className: "badge-sent",
    icon: Send,
  },
  auto_sent: {
    label: "Auto-sent",
    className: "badge-sent",
    icon: Sparkles,
  },
  rejected: {
    label: "Rejected",
    className: "badge-rejected",
  },
};

export default function DraftsPage() {
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["drafts"],
    queryFn: () => draftsApi.list(),
  });

  const approveMutation = useMutation({
    mutationFn: (id: string) => draftsApi.approve(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["drafts"] }),
  });

  const rejectMutation = useMutation({
    mutationFn: (id: string) => draftsApi.reject(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["drafts"] }),
  });

  const drafts = data?.data?.drafts || [];

  return (
    <div className="max-w-4xl">
      {/* Header */}
      <div className="mb-8">
        <h1 className="font-display text-3xl font-semibold tracking-tight">
          Drafts
        </h1>
        <p className="text-muted-foreground mt-1">
          AI-generated responses waiting for your review
        </p>
      </div>

      {/* Content */}
      {isLoading ? (
        <div className="flex flex-col items-center justify-center py-16 text-muted-foreground">
          <div className="h-8 w-8 border-2 border-primary/30 border-t-primary rounded-full animate-spin mb-4" />
          <p>Loading drafts...</p>
        </div>
      ) : drafts.length === 0 ? (
        <div className="flex flex-col items-center justify-center py-16 text-center">
          <div className="h-16 w-16 rounded-2xl bg-accent flex items-center justify-center mb-4">
            <FileEdit className="h-8 w-8 text-muted-foreground" />
          </div>
          <h3 className="font-display text-lg font-medium mb-1">No drafts yet</h3>
          <p className="text-muted-foreground text-sm max-w-sm">
            AI-generated email responses will appear here for your approval
          </p>
        </div>
      ) : (
        <div className="space-y-4">
          {drafts.map((draft: any, index: number) => {
            const status = statusConfig[draft.status] || statusConfig.pending;
            const StatusIcon = status.icon;

            return (
              <div
                key={draft.id}
                className="bg-card rounded-2xl shadow-warm border border-border p-5 transition-soft hover:shadow-warm-lg"
                style={{ animationDelay: `${index * 50}ms` }}
              >
                <div className="flex items-start justify-between gap-4">
                  {/* Content */}
                  <div className="flex-1 min-w-0">
                    {/* Status and time */}
                    <div className="flex items-center gap-2.5 mb-3">
                      <span className={cn("badge", status.className)}>
                        {StatusIcon && <StatusIcon className="h-3 w-3 mr-1" />}
                        {status.label}
                      </span>
                      <span className="text-xs text-muted-foreground">
                        {formatDistanceToNow(new Date(draft.created_at), {
                          addSuffix: true,
                        })}
                      </span>
                    </div>

                    {/* Recipients and subject */}
                    <p className="font-medium text-sm mb-1">
                      To: {draft.to_emails.join(", ")}
                    </p>
                    <p className="text-sm text-muted-foreground truncate mb-3">
                      {draft.subject}
                    </p>

                    {/* Full draft body */}
                    <div className="text-sm text-muted-foreground bg-accent/50 rounded-lg p-3 whitespace-pre-wrap">
                      {draft.body_text}
                    </div>

                    {/* Model attribution */}
                    {draft.llm_model_used && (
                      <div className="flex items-center gap-1.5 mt-3 text-xs text-muted-foreground">
                        <Sparkles className="h-3 w-3" />
                        Generated by {draft.llm_model_used}
                      </div>
                    )}
                  </div>

                  {/* Actions */}
                  {draft.status === "pending" && (
                    <div className="flex flex-col gap-2 shrink-0">
                      <button
                        onClick={() => approveMutation.mutate(draft.id)}
                        disabled={
                          approveMutation.isPending || rejectMutation.isPending
                        }
                        className="flex items-center gap-2 px-4 py-2 bg-success text-success-foreground rounded-xl text-sm font-medium transition-soft hover:opacity-90 disabled:opacity-50"
                        title="Approve and send"
                      >
                        <Check className="h-4 w-4" />
                        Approve
                      </button>
                      <button
                        onClick={() => rejectMutation.mutate(draft.id)}
                        disabled={
                          approveMutation.isPending || rejectMutation.isPending
                        }
                        className="flex items-center gap-2 px-4 py-2 bg-destructive/10 text-destructive rounded-xl text-sm font-medium transition-soft hover:bg-destructive/20 disabled:opacity-50"
                        title="Reject"
                      >
                        <X className="h-4 w-4" />
                        Reject
                      </button>
                    </div>
                  )}
                </div>
              </div>
            );
          })}
        </div>
      )}
    </div>
  );
}
