"use client";

import { useQuery, useMutation, useQueryClient } from "@tanstack/react-query";
import { formatDistanceToNow } from "date-fns";
import { FileEdit, Check, X, RefreshCw } from "lucide-react";
import { draftsApi } from "@/lib/api";
import { cn } from "@/lib/utils";

const statusColors: Record<string, string> = {
  pending: "bg-yellow-500",
  approved: "bg-blue-500",
  sent: "bg-green-500",
  auto_sent: "bg-green-500",
  rejected: "bg-red-500",
};

export default function DraftsPage() {
  const queryClient = useQueryClient();

  const { data, isLoading } = useQuery({
    queryKey: ["drafts"],
    queryFn: () => draftsApi.list(),
  });

  const approveMutation = useMutation({
    mutationFn: (id: string) => draftsApi.approve(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["drafts"] }),
  });

  const rejectMutation = useMutation({
    mutationFn: (id: string) => draftsApi.reject(id),
    onSuccess: () => queryClient.invalidateQueries({ queryKey: ["drafts"] }),
  });

  const drafts = data?.data?.drafts || [];

  return (
    <div>
      <div className="flex items-center justify-between mb-6">
        <h1 className="text-2xl font-bold">Drafts</h1>
      </div>

      {isLoading ? (
        <div className="text-center py-12 text-muted-foreground">
          Loading drafts...
        </div>
      ) : drafts.length === 0 ? (
        <div className="text-center py-12 text-muted-foreground">
          <FileEdit className="h-12 w-12 mx-auto mb-4 opacity-50" />
          <p>No drafts yet</p>
          <p className="text-sm">
            AI-generated email responses will appear here for your approval
          </p>
        </div>
      ) : (
        <div className="border rounded-lg divide-y">
          {drafts.map((draft: any) => (
            <div key={draft.id} className="p-4">
              <div className="flex items-start justify-between gap-4">
                <div className="flex-1 min-w-0">
                  <div className="flex items-center gap-2 mb-1">
                    <span
                      className={cn(
                        "px-2 py-0.5 text-xs font-medium text-white rounded",
                        statusColors[draft.status] || "bg-gray-500"
                      )}
                    >
                      {draft.status}
                    </span>
                    <span className="text-sm text-muted-foreground">
                      {formatDistanceToNow(new Date(draft.created_at), {
                        addSuffix: true,
                      })}
                    </span>
                  </div>
                  <p className="font-medium">To: {draft.to_emails.join(", ")}</p>
                  <p className="text-sm truncate">{draft.subject}</p>
                  {draft.llm_model_used && (
                    <p className="text-xs text-muted-foreground mt-1">
                      Generated by: {draft.llm_model_used}
                    </p>
                  )}
                </div>
                {draft.status === "pending" && (
                  <div className="flex gap-2">
                    <button
                      onClick={() => approveMutation.mutate(draft.id)}
                      disabled={approveMutation.isPending}
                      className="p-2 bg-green-500 text-white rounded-md hover:bg-green-600 disabled:opacity-50"
                      title="Approve and send"
                    >
                      <Check className="h-4 w-4" />
                    </button>
                    <button
                      onClick={() => rejectMutation.mutate(draft.id)}
                      disabled={rejectMutation.isPending}
                      className="p-2 bg-red-500 text-white rounded-md hover:bg-red-600 disabled:opacity-50"
                      title="Reject"
                    >
                      <X className="h-4 w-4" />
                    </button>
                  </div>
                )}
              </div>
            </div>
          ))}
        </div>
      )}
    </div>
  );
}
