"""add guardrails fields to user_settings and drafts

Revision ID: 17984ec2510b
Revises: 2f3f09ba4683
Create Date: 2026-01-14 15:54:59.108770

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '17984ec2510b'
down_revision: Union[str, None] = '2f3f09ba4683'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Add guardrail fields to drafts with server defaults for existing rows
    op.add_column('drafts', sa.Column('guardrail_flagged', sa.Boolean(), nullable=False, server_default=sa.text('false')))
    op.add_column('drafts', sa.Column('guardrail_violations', sa.Text(), nullable=True))
    op.add_column('drafts', sa.Column('llm_confidence', sa.Numeric(precision=4, scale=3), nullable=True))

    # Add guardrail settings to user_settings with server defaults
    op.add_column('user_settings', sa.Column('guardrail_profanity_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('guardrail_pii_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('guardrail_commitment_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('guardrail_custom_keywords_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true')))
    op.add_column('user_settings', sa.Column('guardrail_confidence_threshold', sa.Numeric(precision=3, scale=2), nullable=False, server_default=sa.text('0.70')))
    op.add_column('user_settings', sa.Column('guardrail_blocked_keywords', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user_settings', 'guardrail_blocked_keywords')
    op.drop_column('user_settings', 'guardrail_confidence_threshold')
    op.drop_column('user_settings', 'guardrail_custom_keywords_enabled')
    op.drop_column('user_settings', 'guardrail_commitment_enabled')
    op.drop_column('user_settings', 'guardrail_pii_enabled')
    op.drop_column('user_settings', 'guardrail_profanity_enabled')
    op.drop_column('drafts', 'llm_confidence')
    op.drop_column('drafts', 'guardrail_violations')
    op.drop_column('drafts', 'guardrail_flagged')
    # ### end Alembic commands ###
