"""add batch_draft_jobs table

Revision ID: 2f3f09ba4683
Revises: 7cce982646c9
Create Date: 2026-01-01 12:35:10.395411

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2f3f09ba4683'
down_revision: Union[str, None] = '7cce982646c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('batch_draft_jobs',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('total_emails', sa.Integer(), nullable=False),
    sa.Column('completed_emails', sa.Integer(), nullable=False),
    sa.Column('failed_emails', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('email_ids', postgresql.ARRAY(sa.UUID()), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_batch_draft_jobs_user_id'), 'batch_draft_jobs', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_batch_draft_jobs_user_id'), table_name='batch_draft_jobs')
    op.drop_table('batch_draft_jobs')
    # ### end Alembic commands ###
